### ISSUE TITLE
migrate not working

### ISSUE THREAD

**Issue by knuks** [jplhomer/laravel-realtime-chat-demo#1]
when i migrate the database it gives error 
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long;
max key length is 767 bytes

**Comment by bencomeau** [comment]
@knuks Laravel 5.4 uses the `utf8mb4` character set by default, which is likely causing this issue. If you're running the LTS version of `mariadb` or a MySQL version  `< 5.7.7` then this error will be present. You can either:

- Upgrade to a version that supports the length needed for `utf8mb4`
- Specify `Schema::defaultStringLength(191);` in your `AppServiceProvider` file

Quickest way is the 2nd option and will resolve the error. You can read more about this in the [release notes](https://laravel.com/docs/5.4/releases#laravel-5.4) for 5.4.

**Comment by aqiltariq** [comment]
@bencomeau after chosing second option next error comes which is
 [Symfony\Component\Debug\Exception\FatalErrorException]                      
  Call to undefined method Illuminate\Database\Schema\MySqlBuilder::defaultSt  
  ringLength()

**Comment by bencomeau** [comment]
@aqiltariq What Laravel version are you running? It was introduced in `5.4` so anything less and this method doesn't exist. If on `>=5.4`, then perhaps run a `composer dump-autoload -o` to ensure things are getting loaded properly?

**Comment by aqiltariq** [comment]
![image](https://cloud.githubusercontent.com/assets/8025359/23037357/e0b35352-f4a7-11e6-960b-dc940c22b592.png)
You can see my laravel version is 5.4 and run composer dump-autoload -o command but still there is the error

**Comment by bencomeau** [comment]
@aqiltariq  Hmm. Then I suspect you're not using the correct `Schema` facade in your `AppServiceProvider.php` file. Actually, I believe that's it because your error is stating the method doesn't exist in the `MySqlBuilder` class and that's not where this method actually is.

Make sure you're importing the correct facade: `use Illuminate\Support\ServiceProvider;`

**Comment by aqiltariq** [comment]
![image](https://cloud.githubusercontent.com/assets/8025359/23037886/d7c56fbc-f4a9-11e6-8ab5-7111c0a70afe.png)
@bencomeau using the same facade. but error is still coming as you see in my screenshot

**Comment by bencomeau** [comment]
@aqiltariq Right you are. I'm out of ideas at this point, might try stackoverflow? It should be working since your namespacing is correct.

**Comment by jplhomer** [comment]
Closing this since it's a Laravel 5.4-related issue and not a chat demo issue https://laravel.com/docs/5.4/releases#laravel-5.4
