### ISSUE TITLE
 Pusher not working

### ISSUE THREAD

**Issue by aofdev** [jplhomer/laravel-realtime-chat-demo#2]
** run project** 
use xampp
step 1 npm run watch 
step 2 php artisan serve         //http://127.0.0.1:8000/chat
not working ?
**errors what ?**﻿

**Comment by fhferreira** [comment]
Pusher here needed the change key on file resources/assets/js/bootstrap.js 

```
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: 'yourPusherKeyHere'
});
```
