### ISSUE TITLE
Cluster option

### ISSUE THREAD

**Issue by newuni** [jplhomer/laravel-realtime-chat-demo#3]
First at all, nice work.

Two comments:

1. You should add support to "cluster" options in order to support European users.

```
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: 'xxxxxx',
    cluster: 'eu'
});
```

In bootstrap.js and .env files

2. You should also review resources/assets/js/bootstrap.js, because you Pusher key is exposed:

```
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: 'a0e0f7cd77e818758559'
});
```

Thanks again,

**Comment by vesper8** [comment]
@newuni would you mind sharing how to properly not expose the pusher key ?

**Comment by jplhomer** [comment]
@newuni Thanks for the suggestions! I'm guessing cluster would depend on different users' locations.

And the Pusher key is a public key which would live on the front-end for users - as long as you keep your private key secret, you should be OK.

**Comment by newuni** [comment]
Yes,

I would add a env('PUSHER_CLUSTER', 'mt1') in broadcasting.php, mt1 is the default value https://pusher.com/docs/clusters 

`'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_KEY'),
            'secret' => env('PUSHER_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_CLUSTER', 'mt1')
            ],
        ],`

**Comment by jplhomer** [comment]
@newuni Thanks. Would be awesome if you wanted to put together a PR for this - I'm gonna turn off Issues on the repo since I don't have time to support other questions 😬
