### ISSUE TITLE
Pusher errore 

### ISSUE THREAD

**Issue by anasmorahhib** [jplhomer/laravel-realtime-chat-demo#4]
I changed the key of the pucher,
But it does not work,
i use wampserver

**Comment by jplhomer** [comment]
HI @anasmorahhib what errors do you see? Can you describe what isn't working?

**Comment by anasmorahhib** [comment]
tbks @jplhomer , The numbers of people connected
And when I send a message, it does not appear in the other user, But the message saves on the given database.
![image](https://cloud.githubusercontent.com/assets/16271253/23214739/b6392a8e-f907-11e6-8943-97a519f64cba.png)

**Comment by jplhomer** [comment]
@anasmorahhib Sounds like an issue with Event Broadcasting. I'd be sure to follow all the steps mentioned here: https://www.youtube.com/watch?v=iiBcOKYxd0Q&t=304s Closing this since I unfortunately don't have time to support free projects 😞
