### ISSUE TITLE
No channel connect pusher.

### ISSUE THREAD

**Issue by diz123** [jplhomer/laravel-realtime-chat-demo#5]
Hello, i try following step by step in https://jplhomer.org/2017/01/building-realtime-chat-app-laravel-5-4-vuejs/ and in pusher debug console show me the connect but dont have name of channel. 

So i try download laravel-realtime-chat-demo ,run it, have but the same problem it's not realtime.
Any ideal for that? This is first time i try to create some realtime app. Thanks you!

**Comment by ibrahimSmuhammad** [comment]
I have the same issue :(

**Comment by jplhomer** [comment]
Hey all, sorry - this repo is meant more for reference. Please double check that you've followed all the steps (correct Event name, Pusher setup with keys and cluster name per Pusher docs: https://pusher.com/docs/client_api_guide), and correct environmental variables set (Event Broadcasting set to Pusher and not File, etc).
